### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by ikennarichard**
- Update configs
- Add production url property

### CODE REVIEW

**Comment by mnaibei** [comment]
What's up bro😂., long time no see @ikennarichard

**Comment by ikennarichard** [comment]
@mnaibei My bro!, miss you man, really nice hearing from you, I'm good sir, how about you?
I'm trying to deploy to render, then add the link to the README file

**Comment by mnaibei** [comment]
I'm good too., nothing much happening just trying not to go crazy😂😂., hows the deployment going

**Comment by ikennarichard** [comment]
I go in and out of crazy bro, deployment is going ok, thank God your here, please if you have some time to spare, could you check the commit and see whats the issue with the linters, i think is from the cors file. Thank you @mnaibei

**Comment by mnaibei** [comment]
It's from puma.rb did you run the autocorrect?

**Comment by mnaibei** [comment]
It won't affect functionality

**Comment by ikennarichard** [comment]
Ok bro @mnaibei, let me run the -A cos I already did the -a?

**Comment by mnaibei** [comment]
Yeah., did it work?

**Comment by ikennarichard** [comment]
All good bro, over to react, here's the link to API docs, appointment-app-backend-62lj.onrender.com/api-docs @mnaibei

**Comment by mnaibei** [comment]
I've seen it., good job bro

**Pull request merged**
